const initialData = {
    pieces: {
        'p1': {
            id: "p1",
            name: "Piece 1",
            image: "0.svg",
            time: "60",
            color: '#f7ffb0',
            pause: false,
            visible: true,
            additionalText: '',
            additionalDuration: '',
            messages: {},
        },
        'p2': {
            id: "p2",
            name: "Piece 2",
            image: "1.svg",
            time: "300",
            color: '#ffc1d8',
            pause: false,
            visible: true,
            additionalText: '',
            additionalDuration: '',
            messages: {},
        },
        'p3': {
            id: "p3",
            name: "Piece 3",
            image: "2.svg",
            time: "360",
            color: '#90e4d7',
            pause: false,
            visible: true,
            additionalText: '',
            additionalDuration: '',
            messages: {},
        },
        'p4': {
            id: "p4",
            name: "Piece 4",
            image: "3.svg",
            time: "1800",
            color: '#c4ffa2',
            pause: false,
            visible: true,
            additionalText: '',
            additionalDuration: '',
            messages: {},
        },
    },
    workflows: {
        'w1': { id: 'workflow-1', pieceIDs: ['p3', 'p1', 'p4', 'p2', 'p3'] },
        'w2': { id: 'workflow-2', pieceIDs: ['p3', 'p3', 'p2'] },
        'w3': { id: 'workflow-3', pieceIDs: ['p1', 'p2', 'p4', 'p3', 'p3'] },
        'w4': { id: 'workflow-4', pieceIDs: ['p2', 'p1', 'p1', 'p3', 'p2', 'p3', 'p1', 'p4'] }
    },
    workflowOrder: ['w1', 'w2','w3','w4'],
    starttime: "10:00",
};
export default initialData;